name: ros2-ws-action
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master, feature/fix-github-workflows]
  workflow_run:
    workflows: [Build and Test Nightly]
    types:  [requested, completed, in_progress]
    branches: [feature/fix-github-workflows]
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          path: shisen_cpp

      - name: Checkout Shisen Interface
        uses: actions/checkout@v2.3.4
        with:
          repository: ichiro-its/shisen_interfaces
          path: shisen_interfaces

      - name: Checkout Kansei Interfaces
        uses: actions/checkout@v2.3.4
        with:
          repository: ichiro-its/kansei_interfaces
          path: kansei_interfaces

      - name: install opencv contrib
        run: |
          sudo apt install libopencv-contrib-dev -y

      - name: Checkout Keisan
        uses: actions/checkout@v2.3.4
        with:
          repository: ichiro-its/keisan
          path: keisan

      - name: Setup workspace
        uses: ichiro-its/ros2-ws-action/setup@v1.0.1

      - name: Build workspace
        uses: ichiro-its/ros2-ws-action/build@v1.0.1

      - name: Test workspace
        uses: ichiro-its/ros2-ws-action/test@v1.0.1
